//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBlindsWebApp.sbWebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BlindSettings", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class BlindSettings : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int SysIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SbHorizontalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SbVerticalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NotesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int SysID {
            get {
                return this.SysIDField;
            }
            set {
                if ((this.SysIDField.Equals(value) != true)) {
                    this.SysIDField = value;
                    this.RaisePropertyChanged("SysID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string SbHorizontal {
            get {
                return this.SbHorizontalField;
            }
            set {
                if ((object.ReferenceEquals(this.SbHorizontalField, value) != true)) {
                    this.SbHorizontalField = value;
                    this.RaisePropertyChanged("SbHorizontal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string SbVertical {
            get {
                return this.SbVerticalField;
            }
            set {
                if ((object.ReferenceEquals(this.SbVerticalField, value) != true)) {
                    this.SbVerticalField = value;
                    this.RaisePropertyChanged("SbVertical");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Notes {
            get {
                return this.NotesField;
            }
            set {
                if ((object.ReferenceEquals(this.NotesField, value) != true)) {
                    this.NotesField = value;
                    this.RaisePropertyChanged("Notes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="sbWebService.SmartBlindsWebServiceSoap")]
    public interface SmartBlindsWebServiceSoap {
        
        // CODEGEN: Generating message contract since the wrapper name (TestHelloWorldd) of message TestHelloWorldd does not match the default value (HelloWorld)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TestHelloWorldd", ReplyAction="*")]
        SmartBlindsWebApp.sbWebService.TestHelloWorldd1 HelloWorld(SmartBlindsWebApp.sbWebService.TestHelloWorldd request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TestHelloWorldd", ReplyAction="*")]
        System.Threading.Tasks.Task<SmartBlindsWebApp.sbWebService.TestHelloWorldd1> HelloWorldAsync(SmartBlindsWebApp.sbWebService.TestHelloWorldd request);
        
        // CODEGEN: Generating message contract since element name GetCurrentUserResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCurrentUser", ReplyAction="*")]
        SmartBlindsWebApp.sbWebService.GetCurrentUserResponse GetCurrentUser(SmartBlindsWebApp.sbWebService.GetCurrentUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCurrentUser", ReplyAction="*")]
        System.Threading.Tasks.Task<SmartBlindsWebApp.sbWebService.GetCurrentUserResponse> GetCurrentUserAsync(SmartBlindsWebApp.sbWebService.GetCurrentUserRequest request);
        
        // CODEGEN: Generating message contract since element name GetBlindSettingsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBlindSettings", ReplyAction="*")]
        SmartBlindsWebApp.sbWebService.GetBlindSettingsResponse GetBlindSettings(SmartBlindsWebApp.sbWebService.GetBlindSettingsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBlindSettings", ReplyAction="*")]
        System.Threading.Tasks.Task<SmartBlindsWebApp.sbWebService.GetBlindSettingsResponse> GetBlindSettingsAsync(SmartBlindsWebApp.sbWebService.GetBlindSettingsRequest request);
        
        // CODEGEN: Generating message contract since element name SetBlindSettingsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetBlindSettings", ReplyAction="*")]
        SmartBlindsWebApp.sbWebService.SetBlindSettingsResponse SetBlindSettings(SmartBlindsWebApp.sbWebService.SetBlindSettingsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetBlindSettings", ReplyAction="*")]
        System.Threading.Tasks.Task<SmartBlindsWebApp.sbWebService.SetBlindSettingsResponse> SetBlindSettingsAsync(SmartBlindsWebApp.sbWebService.SetBlindSettingsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TestHelloWorldd", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TestHelloWorldd {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string name;
        
        public TestHelloWorldd() {
        }
        
        public TestHelloWorldd(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TestHelloWorlddResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TestHelloWorldd1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string TestHelloWorlddResult;
        
        public TestHelloWorldd1() {
        }
        
        public TestHelloWorldd1(string TestHelloWorlddResult) {
            this.TestHelloWorlddResult = TestHelloWorlddResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrentUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrentUser", Namespace="http://tempuri.org/", Order=0)]
        public SmartBlindsWebApp.sbWebService.GetCurrentUserRequestBody Body;
        
        public GetCurrentUserRequest() {
        }
        
        public GetCurrentUserRequest(SmartBlindsWebApp.sbWebService.GetCurrentUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetCurrentUserRequestBody {
        
        public GetCurrentUserRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrentUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrentUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public SmartBlindsWebApp.sbWebService.GetCurrentUserResponseBody Body;
        
        public GetCurrentUserResponse() {
        }
        
        public GetCurrentUserResponse(SmartBlindsWebApp.sbWebService.GetCurrentUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCurrentUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetCurrentUserResult;
        
        public GetCurrentUserResponseBody() {
        }
        
        public GetCurrentUserResponseBody(string GetCurrentUserResult) {
            this.GetCurrentUserResult = GetCurrentUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBlindSettingsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBlindSettings", Namespace="http://tempuri.org/", Order=0)]
        public SmartBlindsWebApp.sbWebService.GetBlindSettingsRequestBody Body;
        
        public GetBlindSettingsRequest() {
        }
        
        public GetBlindSettingsRequest(SmartBlindsWebApp.sbWebService.GetBlindSettingsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBlindSettingsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SysID;
        
        public GetBlindSettingsRequestBody() {
        }
        
        public GetBlindSettingsRequestBody(int SysID) {
            this.SysID = SysID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBlindSettingsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBlindSettingsResponse", Namespace="http://tempuri.org/", Order=0)]
        public SmartBlindsWebApp.sbWebService.GetBlindSettingsResponseBody Body;
        
        public GetBlindSettingsResponse() {
        }
        
        public GetBlindSettingsResponse(SmartBlindsWebApp.sbWebService.GetBlindSettingsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBlindSettingsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SmartBlindsWebApp.sbWebService.BlindSettings GetBlindSettingsResult;
        
        public GetBlindSettingsResponseBody() {
        }
        
        public GetBlindSettingsResponseBody(SmartBlindsWebApp.sbWebService.BlindSettings GetBlindSettingsResult) {
            this.GetBlindSettingsResult = GetBlindSettingsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetBlindSettingsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetBlindSettings", Namespace="http://tempuri.org/", Order=0)]
        public SmartBlindsWebApp.sbWebService.SetBlindSettingsRequestBody Body;
        
        public SetBlindSettingsRequest() {
        }
        
        public SetBlindSettingsRequest(SmartBlindsWebApp.sbWebService.SetBlindSettingsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetBlindSettingsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SysID;
        
        public SetBlindSettingsRequestBody() {
        }
        
        public SetBlindSettingsRequestBody(int SysID) {
            this.SysID = SysID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetBlindSettingsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetBlindSettingsResponse", Namespace="http://tempuri.org/", Order=0)]
        public SmartBlindsWebApp.sbWebService.SetBlindSettingsResponseBody Body;
        
        public SetBlindSettingsResponse() {
        }
        
        public SetBlindSettingsResponse(SmartBlindsWebApp.sbWebService.SetBlindSettingsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetBlindSettingsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SmartBlindsWebApp.sbWebService.BlindSettings SetBlindSettingsResult;
        
        public SetBlindSettingsResponseBody() {
        }
        
        public SetBlindSettingsResponseBody(SmartBlindsWebApp.sbWebService.BlindSettings SetBlindSettingsResult) {
            this.SetBlindSettingsResult = SetBlindSettingsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SmartBlindsWebServiceSoapChannel : SmartBlindsWebApp.sbWebService.SmartBlindsWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SmartBlindsWebServiceSoapClient : System.ServiceModel.ClientBase<SmartBlindsWebApp.sbWebService.SmartBlindsWebServiceSoap>, SmartBlindsWebApp.sbWebService.SmartBlindsWebServiceSoap {
        
        public SmartBlindsWebServiceSoapClient() {
        }
        
        public SmartBlindsWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SmartBlindsWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmartBlindsWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmartBlindsWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SmartBlindsWebApp.sbWebService.TestHelloWorldd1 SmartBlindsWebApp.sbWebService.SmartBlindsWebServiceSoap.HelloWorld(SmartBlindsWebApp.sbWebService.TestHelloWorldd request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld(string name) {
            SmartBlindsWebApp.sbWebService.TestHelloWorldd inValue = new SmartBlindsWebApp.sbWebService.TestHelloWorldd();
            inValue.name = name;
            SmartBlindsWebApp.sbWebService.TestHelloWorldd1 retVal = ((SmartBlindsWebApp.sbWebService.SmartBlindsWebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.TestHelloWorlddResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmartBlindsWebApp.sbWebService.TestHelloWorldd1> SmartBlindsWebApp.sbWebService.SmartBlindsWebServiceSoap.HelloWorldAsync(SmartBlindsWebApp.sbWebService.TestHelloWorldd request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmartBlindsWebApp.sbWebService.TestHelloWorldd1> HelloWorldAsync(string name) {
            SmartBlindsWebApp.sbWebService.TestHelloWorldd inValue = new SmartBlindsWebApp.sbWebService.TestHelloWorldd();
            inValue.name = name;
            return ((SmartBlindsWebApp.sbWebService.SmartBlindsWebServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SmartBlindsWebApp.sbWebService.GetCurrentUserResponse SmartBlindsWebApp.sbWebService.SmartBlindsWebServiceSoap.GetCurrentUser(SmartBlindsWebApp.sbWebService.GetCurrentUserRequest request) {
            return base.Channel.GetCurrentUser(request);
        }
        
        public string GetCurrentUser() {
            SmartBlindsWebApp.sbWebService.GetCurrentUserRequest inValue = new SmartBlindsWebApp.sbWebService.GetCurrentUserRequest();
            inValue.Body = new SmartBlindsWebApp.sbWebService.GetCurrentUserRequestBody();
            SmartBlindsWebApp.sbWebService.GetCurrentUserResponse retVal = ((SmartBlindsWebApp.sbWebService.SmartBlindsWebServiceSoap)(this)).GetCurrentUser(inValue);
            return retVal.Body.GetCurrentUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmartBlindsWebApp.sbWebService.GetCurrentUserResponse> SmartBlindsWebApp.sbWebService.SmartBlindsWebServiceSoap.GetCurrentUserAsync(SmartBlindsWebApp.sbWebService.GetCurrentUserRequest request) {
            return base.Channel.GetCurrentUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmartBlindsWebApp.sbWebService.GetCurrentUserResponse> GetCurrentUserAsync() {
            SmartBlindsWebApp.sbWebService.GetCurrentUserRequest inValue = new SmartBlindsWebApp.sbWebService.GetCurrentUserRequest();
            inValue.Body = new SmartBlindsWebApp.sbWebService.GetCurrentUserRequestBody();
            return ((SmartBlindsWebApp.sbWebService.SmartBlindsWebServiceSoap)(this)).GetCurrentUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SmartBlindsWebApp.sbWebService.GetBlindSettingsResponse SmartBlindsWebApp.sbWebService.SmartBlindsWebServiceSoap.GetBlindSettings(SmartBlindsWebApp.sbWebService.GetBlindSettingsRequest request) {
            return base.Channel.GetBlindSettings(request);
        }
        
        public SmartBlindsWebApp.sbWebService.BlindSettings GetBlindSettings(int SysID) {
            SmartBlindsWebApp.sbWebService.GetBlindSettingsRequest inValue = new SmartBlindsWebApp.sbWebService.GetBlindSettingsRequest();
            inValue.Body = new SmartBlindsWebApp.sbWebService.GetBlindSettingsRequestBody();
            inValue.Body.SysID = SysID;
            SmartBlindsWebApp.sbWebService.GetBlindSettingsResponse retVal = ((SmartBlindsWebApp.sbWebService.SmartBlindsWebServiceSoap)(this)).GetBlindSettings(inValue);
            return retVal.Body.GetBlindSettingsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmartBlindsWebApp.sbWebService.GetBlindSettingsResponse> SmartBlindsWebApp.sbWebService.SmartBlindsWebServiceSoap.GetBlindSettingsAsync(SmartBlindsWebApp.sbWebService.GetBlindSettingsRequest request) {
            return base.Channel.GetBlindSettingsAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmartBlindsWebApp.sbWebService.GetBlindSettingsResponse> GetBlindSettingsAsync(int SysID) {
            SmartBlindsWebApp.sbWebService.GetBlindSettingsRequest inValue = new SmartBlindsWebApp.sbWebService.GetBlindSettingsRequest();
            inValue.Body = new SmartBlindsWebApp.sbWebService.GetBlindSettingsRequestBody();
            inValue.Body.SysID = SysID;
            return ((SmartBlindsWebApp.sbWebService.SmartBlindsWebServiceSoap)(this)).GetBlindSettingsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SmartBlindsWebApp.sbWebService.SetBlindSettingsResponse SmartBlindsWebApp.sbWebService.SmartBlindsWebServiceSoap.SetBlindSettings(SmartBlindsWebApp.sbWebService.SetBlindSettingsRequest request) {
            return base.Channel.SetBlindSettings(request);
        }
        
        public SmartBlindsWebApp.sbWebService.BlindSettings SetBlindSettings(int SysID) {
            SmartBlindsWebApp.sbWebService.SetBlindSettingsRequest inValue = new SmartBlindsWebApp.sbWebService.SetBlindSettingsRequest();
            inValue.Body = new SmartBlindsWebApp.sbWebService.SetBlindSettingsRequestBody();
            inValue.Body.SysID = SysID;
            SmartBlindsWebApp.sbWebService.SetBlindSettingsResponse retVal = ((SmartBlindsWebApp.sbWebService.SmartBlindsWebServiceSoap)(this)).SetBlindSettings(inValue);
            return retVal.Body.SetBlindSettingsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmartBlindsWebApp.sbWebService.SetBlindSettingsResponse> SmartBlindsWebApp.sbWebService.SmartBlindsWebServiceSoap.SetBlindSettingsAsync(SmartBlindsWebApp.sbWebService.SetBlindSettingsRequest request) {
            return base.Channel.SetBlindSettingsAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmartBlindsWebApp.sbWebService.SetBlindSettingsResponse> SetBlindSettingsAsync(int SysID) {
            SmartBlindsWebApp.sbWebService.SetBlindSettingsRequest inValue = new SmartBlindsWebApp.sbWebService.SetBlindSettingsRequest();
            inValue.Body = new SmartBlindsWebApp.sbWebService.SetBlindSettingsRequestBody();
            inValue.Body.SysID = SysID;
            return ((SmartBlindsWebApp.sbWebService.SmartBlindsWebServiceSoap)(this)).SetBlindSettingsAsync(inValue);
        }
    }
}
