//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBlindsWebApp.WIN100TEST {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WIN100TEST.WIN1500TESTSoap")]
    public interface WIN1500TESTSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        SmartBlindsWebApp.WIN100TEST.HelloWorldResponse HelloWorld(SmartBlindsWebApp.WIN100TEST.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<SmartBlindsWebApp.WIN100TEST.HelloWorldResponse> HelloWorldAsync(SmartBlindsWebApp.WIN100TEST.HelloWorldRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public SmartBlindsWebApp.WIN100TEST.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(SmartBlindsWebApp.WIN100TEST.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public SmartBlindsWebApp.WIN100TEST.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(SmartBlindsWebApp.WIN100TEST.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WIN1500TESTSoapChannel : SmartBlindsWebApp.WIN100TEST.WIN1500TESTSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WIN1500TESTSoapClient : System.ServiceModel.ClientBase<SmartBlindsWebApp.WIN100TEST.WIN1500TESTSoap>, SmartBlindsWebApp.WIN100TEST.WIN1500TESTSoap {
        
        public WIN1500TESTSoapClient() {
        }
        
        public WIN1500TESTSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WIN1500TESTSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WIN1500TESTSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WIN1500TESTSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SmartBlindsWebApp.WIN100TEST.HelloWorldResponse SmartBlindsWebApp.WIN100TEST.WIN1500TESTSoap.HelloWorld(SmartBlindsWebApp.WIN100TEST.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            SmartBlindsWebApp.WIN100TEST.HelloWorldRequest inValue = new SmartBlindsWebApp.WIN100TEST.HelloWorldRequest();
            inValue.Body = new SmartBlindsWebApp.WIN100TEST.HelloWorldRequestBody();
            SmartBlindsWebApp.WIN100TEST.HelloWorldResponse retVal = ((SmartBlindsWebApp.WIN100TEST.WIN1500TESTSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmartBlindsWebApp.WIN100TEST.HelloWorldResponse> SmartBlindsWebApp.WIN100TEST.WIN1500TESTSoap.HelloWorldAsync(SmartBlindsWebApp.WIN100TEST.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmartBlindsWebApp.WIN100TEST.HelloWorldResponse> HelloWorldAsync() {
            SmartBlindsWebApp.WIN100TEST.HelloWorldRequest inValue = new SmartBlindsWebApp.WIN100TEST.HelloWorldRequest();
            inValue.Body = new SmartBlindsWebApp.WIN100TEST.HelloWorldRequestBody();
            return ((SmartBlindsWebApp.WIN100TEST.WIN1500TESTSoap)(this)).HelloWorldAsync(inValue);
        }
    }
}
